import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Physical AI & Humanoid Robotics E-Book
 *
 * Structure:
 * - Introduction
 * - Module 1: ROS 2 Foundation
 * - Module 2: Simulation (Gazebo & Unity)
 * - Module 3: Isaac AI (NVIDIA Isaac Sim)
 * - Module 4: VLA Integration (Vision-Language-Action)
 * - Module 5: Hardware Deployment
 * - Capstone Project
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Foundation',
      link: {
        type: 'doc',
        id: 'module-01-ros2/module-01-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-01-ros2'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Mastery',
      link: {
        type: 'doc',
        id: 'module-02-simulation/module-02-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-02-simulation'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Powered Perception & Navigation',
      link: {
        type: 'doc',
        id: 'module-03-isaac-ai/module-03-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-03-isaac-ai'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Integration',
      link: {
        type: 'doc',
        id: 'module-04-vla/module-04-index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-04-vla'},
      ],
    },
    // Module 5 and Capstone will be added as they're implemented
  ],
};

export default sidebars;
